Repository wright-group/WrightTools, pull requests merged in 2018-06, with the labels that each got.

#603 3.0.3
  WrightTools/VERSION
  requirements.txt
  setup.py
Labels: enhancement

#604 add MANIFEST
  MANIFEST.in
Labels: bug

#605 Remotely fetch logo so it apears on PyPI
  README.rst
Labels: documentation

#606 3.0.4
  MANIFEST.in
  README.rst
  WrightTools/VERSION
Labels: enhancement

#613 Add multiprocessing to tests
  .travis.yml
  docs/contributing.rst
  tests/docs/_sphinx.py
  tests/kit/ini.py
Labels: tests

#627 cleanup artists
  WrightTools/artists/_absorbance.py
  WrightTools/artists/_diff2d.py
  WrightTools/artists/_pdf2dslices.py
Labels: cleanup

#628 add citation
  WrightTools/CITATION
  WrightTools/__citation__.py
  WrightTools/__init__.py
  docs/publications.rst
  tests/citation.py
Labels: documentation

#638 axes methods return
  WrightTools/artists/_base.py
Labels: bug

#646 allow mag as a kwarg to normalize
  WrightTools/data/_channel.py
  tests/data/channel/normalize.py
Labels: enhancement
