Repository wright-group/WrightTools, pull requests merged in 2018-11, with the labels that each got.

#772 wisconsin–madison
  .zenodo.json
Labels: annoyance

#768 BUG: fix expected units behavior in from_PyCMDS
  WrightTools/data/_pycmds.py
  tests/data/axis/convert_axis.py
  tests/data/convert_data.py
  tests/data/get_nadir.py
  tests/data/get_zenith.py
Labels: bug

#775 ENH: Add temperature units, including from_Cary
  WrightTools/collection/_cary.py
  WrightTools/units.py
Labels: enhancement

#776 ENH: Gradient as a method of data
  WrightTools/data/_data.py
  docs/data.rst
  examples/gradient.py
  tests/data/gradient.py
Labels: enhancement

#778 DOC: Update units documentation
  WrightTools/units.py
  docs/units.rst
Labels: documentation

#784 Quick1D range, pad with a little extra space
  WrightTools/artists/_quick.py
Labels: artists, enhancement

#785 ENH: Add Figure title with data name
  WrightTools/artists/_quick.py
Labels: artists, enhancement

#787 correct symmetric_root call in examples and tests
  examples/colormaps.py
  examples/fill_types.py
  examples/fringes_transform.py
  examples/label_delay_space.py
  examples/level.py
  tests/artists/test_contour.py
  tests/artists/test_pcolor.py
  tests/artists/test_plot.py
Labels: bug, documentation

#788 clip out negative pixels in label_delay_space
  examples/label_delay_space.py
Labels: annoyance, documentation

#790 add default_aspect to docstring
  WrightTools/artists/_helpers.py
Labels: documentation

#791 set_fig_labels enhancements
  WrightTools/artists/_helpers.py
Labels: artists, enhancement

#789 BUG: Allow from_Cary to read data with duplicate names
  WrightTools/collection/_cary.py
  examples/filters.py
  tests/collection/from_cary.py
  tests/data/test_data/duplicate_name.csv
Labels: bug

#794 Clean up _instances
  WrightTools/_dataset.py
  WrightTools/_group.py
  WrightTools/data/_data.py
  tests/base.py
Labels: bug, cleanup

#799 Handali2018
  docs/citation.rst
  docs/index.rst
Labels: documentation

#796 clip data for level example
  examples/level.py
Labels: documentation

#800 ENH: Use natural_name setter to rename item in hdf5 file
  WrightTools/_dataset.py
  WrightTools/_group.py
  tests/base.py
Labels: enhancement

#807 DOC: map-variable example
  examples/map-variable.py
Labels: documentation

#786 ENH: Implementation of moment
  WrightTools/data/_data.py
  docs/data.rst
  tests/data/moment.py
Labels: enhancement

#805 DOC: TEST: heal
  examples/heal.py
  tests/data/heal.py
Labels: documentation, tests

#806 DOC: Data doc improvements
  docs/data.rst
Labels: documentation
