Repository wright-group/WrightTools, pull requests merged in 2018-02, with the labels that each got.

#386 [WIP] Cary HDF5
  WrightTools/collection/__init__.py
  WrightTools/collection/_cary.py
  WrightTools/kit/_utilities.py
  tests/data/from_Cary50.py
Labels: tests

#467 print_tree tuneup
  WrightTools/collection/_collection.py
  WrightTools/data/_axis.py
  WrightTools/data/_data.py
Labels: enhancement

#468 tensor27
  WrightTools/data/_tensor27.py
  tests/data/from_Tensor27.py
Labels: enhancement

#470 recover spcm
  WrightTools/data/_spcm.py
  tests/data/from_spcm.py
Labels: enhancement

#471 [WIP] remove test.ini
  tests/dataset/clip.py
  tests/kit/ini.py
Labels: enhancement

#492 level
  WrightTools/data/_data.py
  WrightTools/exceptions.py
  tests/data/level.py
Labels: enhancement

#489 Arg min, arg max, sharenans
  WrightTools/_dataset.py
  WrightTools/data/_data.py
  tests/data/get_nadir.py
  tests/data/get_zenith.py
  tests/data/share_nans.py
  tests/dataset/argmax.py
  tests/dataset/argmin.py
  tests/dataset/max.py
  tests/dataset/min.py
Labels: enhancement

#490 examples and artists cleanup
  WrightTools/artists/__init__.py
  WrightTools/artists/_base.py
  WrightTools/artists/_colors.py
  WrightTools/artists/_helpers.py
  WrightTools/artists/_quick.py
  WrightTools/data/_colors.py
  WrightTools/data/_data.py
  WrightTools/datasets/PyCMDS/d1 d2 000.data
  WrightTools/datasets/PyCMDS/d1 d2 001.data
  WrightTools/diagrams/WMEL.py
  WrightTools/diagrams/delay.py
  broken_examples/absorbance.py
  broken_examples/batch_4_comparison.py
  broken_examples/quick1D.py
  examples/colormaps.py
  examples/fill_types.py
  examples/fringes_transform.py
  examples/label_delay_space.py
  examples/level.py
  examples/quick1D.py
  examples/rRaman.py
  examples/tune_test.py
Labels: enhancement

#500 add publications
  docs/index.rst
  docs/publications.rst
Labels: documentation

#494 Add from_directory function
  WrightTools/_group.py
  WrightTools/collection/__init__.py
  WrightTools/collection/_cary.py
  WrightTools/collection/_collection.py
  WrightTools/collection/_directory.py
  WrightTools/data/_brunold.py
  WrightTools/data/_data.py
  WrightTools/data/_jasco.py
  WrightTools/data/_pycmds.py
  WrightTools/data/_shimadzu.py
  WrightTools/datasets/Cary/CuPCtS_H2O_vis.csv
  WrightTools/datasets/__init__.py
  docs/datasets.rst
  tests/collection/from_directory.py
  tests/data/level.py
Labels: enhancement

#512 Copy fix
  WrightTools/_group.py
  tests/group/save.py
Labels: bug

#513 Darien's little fixes.
  WrightTools/data/_data.py
  WrightTools/units.py
Labels: enhancement

#514 Add encode
  WrightTools/_group.py
Labels: bug

#515 Travis building with pip
  .travis.yml
  WrightTools/__init__.py
  setup.py
Labels: enhancement, tests

#427 join
  WrightTools/_dataset.py
  WrightTools/data/_data.py
  WrightTools/data/_join.py
  tests/data/join.py
Labels: enhancement

#516 Name conflict
  WrightTools/data/_join.py
  tests/data/join.py
Labels: bug
