Repository wright-group/WrightTools, pull requests merged in 2018-07, with the labels that each got.

#660 Downscale
  WrightTools/data/_data.py
  setup.py
  tests/data/downscale.py
Labels: enhancement

#662 remove apparently unnecessary hdf package installs
  .travis.yml
Labels: optimization, tests

#666 add specutils to alternatives
  .gitignore
  docs/alternatives.rst
Labels: documentation

#665 fluence calculations (resolves #625)
  WrightTools/data/_data.py
  WrightTools/kit/_calculate.py
  tests/kit/fluence.py
Labels: enhancement

#669 kit.svd
  WrightTools/kit/_array.py
  setup.cfg
  tests/kit/svd.py
Labels: enhancement
