Repository wright-group/WrightTools, pull requests merged in 2018-12, with the labels that each got.

#797 clip data for fill_types example
  examples/fill_types.py
Labels: documentation

#818 BUG: remove print statement for signing channels
  WrightTools/data/_pycmds.py
Labels: bug

#814 BUG: Add back str to isinstance check
  WrightTools/_group.py
Labels: bug

#819 DEP: Deprecate integrate method of collapse
  WrightTools/data/_data.py
Labels: cleanup

#823 BUG, MAINT: __dict__.pop --> delattr
  WrightTools/data/_data.py
Labels: bug, cleanup

#822 BUG: Fix PyCMDS reading data with None Units
  WrightTools/data/_pycmds.py
Labels: bug

#829 Recover trim
  WrightTools/data/_channel.py
  tests/data/trim.py
Labels: enhancement

#825 DOC: Split api into separate files
  WrightTools/data/_data.py
  WrightTools/data/_spcm.py
  WrightTools/kit/_timestamp.py
  docs/api/.gitignore
  docs/api/WrightTools.artists.Axes.rst
  docs/api/WrightTools.artists.Figure.rst
  docs/api/WrightTools.artists.GridSpec.rst
  docs/api/WrightTools.artists.rst
  docs/api/WrightTools.collection.Collection.rst
  docs/api/WrightTools.collection.rst
  docs/api/WrightTools.data.Axis.rst
  docs/api/WrightTools.data.Channel.rst
  docs/api/WrightTools.data.Constant.rst
  docs/api/WrightTools.data.Data.rst
  docs/api/WrightTools.data.Variable.rst
  docs/api/WrightTools.data.rst
  docs/api/WrightTools.exceptions.rst
  docs/api/WrightTools.kit.INI.rst
  docs/api/WrightTools.kit.Spline.rst
  docs/api/WrightTools.kit.TimeStamp.rst
  docs/api/WrightTools.kit.Timer.rst
  docs/api/WrightTools.kit.rst
  docs/api/WrightTools.units.rst
  docs/api/modules.rst
  docs/conf.py
Labels: JOSS required, documentation

#833 DOC: clarify subclassed returns in create_figure
  WrightTools/artists/_helpers.py
Labels: documentation

#835 remove diagrams.rst
  docs/diagrams.rst
Labels: cleanup, documentation

#836 remove kit.rst
  docs/index.rst
  docs/kit.rst
Labels: cleanup, documentation

#834 spelling
  docs/wt5.rst
Labels: documentation

#837 create collection.rst
  docs/collection.rst
  docs/index.rst
  docs/wt5.rst
Labels: documentation

#803 DOC: Custom figure documentation and example
  docs/artists.rst
  docs/data.rst
  examples/custom_fig.py
Labels: documentation

#840 improve quickstart
  docs/index.rst
  docs/quickstart.rst
Labels: documentation

#842 spelling collections.rst
  docs/collection.rst
Labels: documentation

#843 DOC: Use literalinclude for citation
  docs/citation.rst
Labels: documentation

#841 improve data
  docs/data.rst
Labels: documentation

#845 DOC: More formal wt5 description
  docs/wt5.rst
Labels: documentation

#844 DOC: DJM doc edits
  docs/api/WrightTools.artists.rst
  docs/api/WrightTools.collection.rst
  docs/api/WrightTools.data.rst
  docs/api/WrightTools.exceptions.rst
  docs/api/WrightTools.kit.rst
  docs/api/WrightTools.units.rst
  docs/artists.rst
  docs/collection.rst
  docs/quickstart.rst
  docs/write_from_function.rst
Labels: documentation

#848 MAINT: Remove pytz dependency
  WrightTools/kit/_timestamp.py
  scripts/recipe/meta.yaml
  setup.py
Labels: cleanup

#846 ENH: make Group objects context managers, close at exit
  WrightTools/_group.py
  tests/base.py
Labels: enhancement

#849 MAINT: Alias convert to converter because it is less confusing
  WrightTools/units.py
Labels: annoyance

#847 MAINT: Remove deprecated rcparam: text.latex.unicode
  WrightTools/artists/_base.py
  setup.py
Labels: cleanup, documentation
