Repository wright-group/WrightTools, pull requests merged in 2018-03, with the labels that each got.

#517 change default axes in quick2D
  WrightTools/artists/_quick.py
  examples/fringes_transform.py
Labels: enhancement

#525 move logo
  README.rst
Labels: documentation

#523 Created time
  WT5_VERSION
  WrightTools/__init__.py
  WrightTools/__wt5_version__.py
  WrightTools/_group.py
  WrightTools/data/_pycmds.py
  setup.py
  tests/data/created.py
Labels: enhancement

#526 Transform
  WrightTools/collection/_cary.py
  WrightTools/data/_brunold.py
  WrightTools/data/_colors.py
  WrightTools/data/_data.py
  WrightTools/data/_jasco.py
  WrightTools/data/_join.py
  WrightTools/data/_kent.py
  WrightTools/data/_ocean_optics.py
  WrightTools/data/_pycmds.py
  WrightTools/data/_shimadzu.py
  WrightTools/data/_spcm.py
  WrightTools/data/_tensor27.py
  examples/fringes_transform.py
  examples/tune_test.py
  tests/data/smooth.py
  tests/data/transform.py
  tests/group/attributes.py
  tests/group/save.py
Labels: enhancement

#527 doc minor updates
  docs/data.rst
  docs/index.rst
  docs/install.rst
  docs/units.rst
Labels: documentation

#524 map_variable
  WrightTools/_dataset.py
  WrightTools/artists/_base.py
  WrightTools/artists/_helpers.py
  WrightTools/data/_axis.py
  WrightTools/data/_data.py
  WrightTools/kit/_array.py
  tests/data/map_variable.py
  tests/data/split.py
  tests/kit/joint_shape.py
  tests/kit/remove_nans_1D.py
  tests/kit/share_nans.py
Labels: enhancement

#533 Sphinx warnings
  WrightTools/data/__init__.py
  WrightTools/data/_data.py
  WrightTools/kit/_list.py
  docs/api/WrightTools.data.rst
  docs/api/modules.rst
  docs/index.rst
Labels: documentation

#534 Remove nans additional test and reimplementation
  WrightTools/kit/_array.py
  tests/kit/remove_nans_1D.py
Labels: bug

#543 allow for constants in variables
  WrightTools/data/_axis.py
  tests/data/transform.py
Labels: bug

#548 few more tests
  tests/data/transform.py
Labels: tests

#552 null settr
  WrightTools/data/_channel.py
  tests/data/channel/null.py
Labels: enhancement

#555 remove appdirs dependency
  requirements.txt
Labels: enhancement

#562 remove redundant natural name
  WrightTools/data/_axis.py
  WrightTools/data/_channel.py
Labels: cleanup

#561 remove info
  WrightTools/data/_data.py
Labels: cleanup

#559 level now works with more than zeroth channel. (resolves #558)
  WrightTools/data/_data.py
  tests/data/level.py
Labels: bug

#544 signed channel handling fixes
  WrightTools/artists/_quick.py
  WrightTools/data/_data.py
  WrightTools/datasets/__init__.py
  WrightTools/datasets/wt5/v1.0.0/perovskite_TA.wt5
  examples/quick2D_signed.py
  tests/data/chop.py
Labels: bug, documentation

#564 remove empty subscripts in labels
  WrightTools/data/_axis.py
Labels: bug

#565 propagate KENT labels
  WrightTools/data/_kent.py
Labels: enhancement

#566 requires 3.5 or newer
  docs/install.rst
Labels: documentation

#568 update timestamp repr
  WrightTools/kit/_timestamp.py
Labels: annoyance

#567 stop encoding strings in attrs
  WT5_VERSION
  WrightTools/_dataset.py
  WrightTools/_group.py
  WrightTools/data/_data.py
  docs/wt5.rst
Labels: cleanup

#572 plot colormap components
  WrightTools/artists/_colors.py
  examples/plot_colormap_components.py
Labels: documentation

#577 update diagonal_line behavior
  WrightTools/artists/_helpers.py
Labels: enhancement
