Repository wright-group/WrightTools, pull requests merged in 2018-08, with the labels that each got.

#670 interact2D
  WrightTools/artists/__init__.py
  WrightTools/artists/_base.py
  WrightTools/artists/_helpers.py
  WrightTools/artists/_interact.py
  WrightTools/artists/_quick.py
  WrightTools/data/_data.py
  WrightTools/data/_solis.py
  setup.py
  tests/artists/test_interact2D.py
  tests/data/chop.py
Labels: artists, enhancement

#689 Fix documentation in quickstart
  docs/quickstart.rst
Labels: documentation

#688 Label gen
  WrightTools/data/_axis.py
  tests/data/labels.py
Labels: bug

#682 Lgtm fixes
  WrightTools/artists/_base.py
  WrightTools/artists/_helpers.py
  WrightTools/data/_axis.py
  WrightTools/data/_channel.py
  WrightTools/data/_colors.py
  WrightTools/data/_jasco.py
  WrightTools/data/_join.py
  WrightTools/data/_kent.py
  WrightTools/data/_shimadzu.py
  WrightTools/data/_solis.py
  WrightTools/data/_variable.py
  WrightTools/diagrams/WMEL.py
Labels: bug, cleanup

#700 Update how we get axis removal to match upstream
  WrightTools/artists/_base.py
Labels: artists, cleanup

#702 From spcm
  WrightTools/data/_spcm.py
  WrightTools/datasets/spcm/test_data_full_metadata.asc
  docs/datasets.rst
  tests/data/from_spcm.py
Labels: enhancement

#698 Implementation of split in WT3
  WrightTools/_dataset.py
  WrightTools/data/_axis.py
  WrightTools/data/_data.py
  WrightTools/kit/_array.py
  WrightTools/kit/_list.py
  docs/datasets.rst
  docs/quickstart.rst
  examples/split.py
  setup.py
  tests/data/split.py
Labels: JOSS required, enhancement

#709 Axis units clean up
  WrightTools/data/_axis.py
  WrightTools/units.py
Labels: bug, cleanup

#706 Type hints
  WrightTools/data/_axis.py
  WrightTools/data/_brunold.py
  WrightTools/data/_channel.py
  WrightTools/data/_data.py
  WrightTools/data/_jasco.py
  WrightTools/data/_join.py
  WrightTools/data/_kent.py
  WrightTools/data/_ocean_optics.py
  WrightTools/data/_pycmds.py
  WrightTools/data/_shimadzu.py
  WrightTools/data/_solis.py
  WrightTools/data/_spcm.py
  WrightTools/data/_tensor27.py
  WrightTools/data/_variable.py
  WrightTools/kit/_array.py
  WrightTools/kit/_calculate.py
  WrightTools/kit/_discover_dimensions.py
  WrightTools/kit/_ini.py
  WrightTools/units.py
Labels: enhancement

#722 Issue 699
  WrightTools/artists/_interact.py
  tests/artists/test_interact2D.py
Labels: enhancement

#725 bump version to 3.1.3
  WrightTools/VERSION
Labels: enhancement

#726 Proper source of the generic "Group"
  WrightTools/_open.py
Labels: bug, cleanup
