Repository wright-group/WrightTools, pull requests merged in 2019-08, with the labels that each got.

#915 Travis deployment automation
  .travis.yml
  scripts/checklists.org
Labels: optimization

#914 Update status badge for conda forge
  docs/index.rst
Labels: annoyance, cleanup

#916 Arrow direction handling
  WrightTools/diagrams/WMEL.py
Labels: annoyance, artists

#830 ENH: Binary ngc file parser
  WrightTools/data/__init__.py
  WrightTools/data/_aramis.py
  docs/api/WrightTools.data.rst
  docs/data.rst
  docs/write_from_function.rst
  tests/data/from_Aramis.py
  tests/data/test_data/circular_map.ngc
  tests/data/test_data/ellipsoidal_map.ngc
  tests/data/test_data/irregular_map.ngc
  tests/data/test_data/rectangular_map.ngc
  tests/data/test_data/skew_line.ngc
  tests/data/test_data/square_map.ngc
  tests/data/test_data/vertical_linescan.ngc
Labels: enhancement

#908 Large file parsing in PyCMDS
  WrightTools/data/_pycmds.py
  tests/data/from_PyCMDS.py
Labels: enhancement

#918 Black repo link (again)
  .pre-commit-config.yaml
  README.rst
Labels: cleanup

#919 Update joss link, add badge to table
  docs/index.rst
Labels: annoyance, cleanup, documentation

#921 no collapse verbose
  WrightTools/data/_pycmds.py
Labels: annoyance
