Repository wright-group/WrightTools, pull requests merged in 2019-01, with the labels that each got.

#853 DOC: add link to contributing docs in CONTRIBUTORS
  CONTRIBUTORS
Labels: JOSS required, documentation

#850 DOC: add `plt.show` to quickstart examples source
  docs/quickstart.rst
Labels: JOSS required, documentation

#854 data.prune() does not work correctly when passing a bare string
  WrightTools/data/_data.py
  tests/data/prune.py
Labels: bug

#856 remove hdf5 tag
  paper/paper.md
Labels: documentation

#857 MAINT/TST: remove multiprocessing from tests
  .travis.yml
Labels: tests

#855 update alternatives page
  docs/alternatives.rst
Labels: JOSS required, documentation

#859 ENH: recover contour in Quick2D (resolves #815)
  WrightTools/artists/_quick.py
Labels: artists, cleanup

#864 update to reflect JOSS publication
  README.rst
  WrightTools/CITATION
  docs/citation.rst
  docs/index.rst
Labels: documentation

#867 ENH: update fluence for another calculation type
  WrightTools/kit/_calculate.py
  tests/kit/fluence.py
Labels: enhancement

#869 fix nm_p conversion
  WrightTools/units.py
Labels: bug
